name: EBAC PAGES

on: push

jobs:
  k6-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run K6 tests
        run: |
          npm install -g k6
          k6 run your-k6-test.js
